import { ActionRegistry } from './action-registry';
import type { ProductAction } from './action-types';

const SIDEBAR_PERMISSIONS = ['activeTab', 'sidePanel', 'storage'];

export const FIRST_PARTY_ACTIONS: readonly ProductAction[] = [
  action({
    aliases: ['sum', 'summ', 'summary', 'tldr', 'brief'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Page summary' },
      { format: 'Checklist', title: 'Next actions' },
    ],
    category: 'research',
    description: 'Extract key points, decisions, and next actions from the current page.',
    estimatedDurationSec: 18,
    executionPlan: [
      step('read-page', 'Read page', 'Capture visible title, structure, and main content.'),
      step('identify-signals', 'Identify signals', 'Find decisions, facts, claims, and open questions.'),
      step('write-summary', 'Write summary', 'Generate a concise answer-first summary.'),
    ],
    icon: 'document',
    id: 'page.summarize',
    popularity: 0.86,
    requiredAiTools: ['summarization'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    shortcut: 'Mod+Shift+S',
    suggestedFollowUps: [
      { actionId: 'memory.saveContext', title: 'Save To Memory' },
      { actionId: 'research.topic', title: 'Research Topic' },
    ],
    supportedContexts: [{ pageKinds: ['article', 'document', 'generic', 'pdf'] }],
    tags: ['page', 'summary', 'research'],
    title: 'Summarize Page',
  }),
  action({
    aliases: ['pr', 'pull request', 'review code', 'github review'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Review notes' },
      { format: 'Checklist', title: 'Risks and missing tests' },
    ],
    category: 'coding',
    description: 'Review a pull request for risks, regressions, and missing tests.',
    estimatedDurationSec: 35,
    executionPlan: [
      step('read-diff', 'Read changed files', 'Inspect changed files and visible discussion context.'),
      step('assess-risk', 'Assess risk', 'Identify correctness, security, and test coverage risks.'),
      step('draft-review', 'Draft review', 'Produce prioritized findings and a concise summary.'),
    ],
    icon: 'git',
    id: 'github.reviewPr',
    popularity: 0.82,
    requiredAiTools: ['code-analysis', 'summarization'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'code.generateTests', title: 'Generate Tests' },
      { actionId: 'github.generateCommit', title: 'Generate Commit' },
    ],
    supportedContexts: [{ hostIncludes: ['github.com'] }],
    tags: ['github', 'pull request', 'review'],
    title: 'Review PR',
  }),
  action({
    aliases: ['function', 'explain code', 'what does this do'],
    artifactsProduced: [{ format: 'Markdown', title: 'Code explanation' }],
    category: 'coding',
    description: 'Explain selected code, logs, errors, or stack traces.',
    estimatedDurationSec: 14,
    executionPlan: [
      step('read-selection', 'Read selection', 'Capture selected text and nearby page context.'),
      step('classify', 'Classify content', 'Detect code, logs, stack traces, or prose.'),
      step('explain', 'Explain clearly', 'Explain behavior, risk, and next debugging steps.'),
    ],
    icon: 'code',
    id: 'selection.explain',
    popularity: 0.78,
    requiredAiTools: ['code-analysis'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'code.findBug', title: 'Explain Bug' },
      { actionId: 'code.generateTests', title: 'Generate Tests' },
    ],
    supportedContexts: [{ requiresSelection: true }, { pageKinds: ['code'] }],
    tags: ['selection', 'code', 'error', 'debug'],
    title: 'Explain Error Or Code',
  }),
  action({
    aliases: ['bug', 'issue', 'debug', 'error', 'defect'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Bug explanation' },
      { format: 'Checklist', title: 'Debug checklist' },
    ],
    category: 'coding',
    description: 'Find likely bugs, edge cases, and root causes in the current code context.',
    estimatedDurationSec: 28,
    executionPlan: [
      step('inspect-context', 'Inspect context', 'Read selected code, errors, or current developer page.'),
      step('trace-failure', 'Trace failure', 'Reason through likely failure paths and assumptions.'),
      step('recommend-fix', 'Recommend fix', 'Return probable causes and concrete fixes.'),
    ],
    icon: 'bug',
    id: 'code.findBug',
    popularity: 0.74,
    requiredAiTools: ['code-analysis', 'debugging'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'code.generateTests', title: 'Generate Tests' },
      { actionId: 'selection.explain', title: 'Explain Code' },
    ],
    supportedContexts: [{ pageKinds: ['code'] }, { requiresSelection: true }],
    tags: ['debug', 'bug', 'code'],
    title: 'Explain Bug',
  }),
  action({
    aliases: ['tests', 'unit tests', 'test cases'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Test plan' },
      { format: 'Checklist', title: 'Coverage checklist' },
    ],
    category: 'coding',
    description: 'Generate a focused test plan for the current code or pull request.',
    estimatedDurationSec: 30,
    executionPlan: [
      step('read-behavior', 'Read behavior', 'Infer intended behavior from code and page context.'),
      step('identify-cases', 'Identify cases', 'Find happy paths, edge cases, and regressions.'),
      step('write-tests', 'Write test plan', 'Produce concrete test cases and coverage notes.'),
    ],
    icon: 'list',
    id: 'code.generateTests',
    popularity: 0.68,
    requiredAiTools: ['code-analysis', 'test-generation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'github.reviewPr', title: 'Review PR' }],
    supportedContexts: [{ pageKinds: ['code'] }, { hostIncludes: ['github.com'] }],
    tags: ['tests', 'code', 'quality'],
    title: 'Generate Tests',
  }),
  action({
    aliases: ['docs', 'readme', 'documentation'],
    artifactsProduced: [{ format: 'Markdown', title: 'Generated documentation' }],
    category: 'coding',
    description: 'Generate documentation from the current code, repository, or product context.',
    estimatedDurationSec: 32,
    executionPlan: [
      step('read-structure', 'Read structure', 'Identify the important concepts and APIs.'),
      step('organize-docs', 'Organize docs', 'Choose headings and examples for the target reader.'),
      step('draft-docs', 'Draft documentation', 'Generate documentation that can be copied or saved.'),
    ],
    icon: 'document',
    id: 'content.generateDocumentation',
    popularity: 0.62,
    requiredAiTools: ['writing', 'code-analysis'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'memory.saveContext', title: 'Save To Memory' }],
    supportedContexts: [{ pageKinds: ['code', 'document', 'generic'] }],
    tags: ['documentation', 'writing', 'code'],
    title: 'Generate Documentation',
  }),
  action({
    aliases: ['repo summary', 'repository', 'summarize repo'],
    artifactsProduced: [{ format: 'Markdown', title: 'Repository summary' }],
    category: 'coding',
    description: 'Summarize repository purpose, structure, and important files.',
    estimatedDurationSec: 25,
    executionPlan: [
      step('read-repo', 'Read repository', 'Use visible README, navigation, and file context.'),
      step('map-structure', 'Map structure', 'Identify architecture, entry points, and ownership areas.'),
      step('summarize-repo', 'Summarize repository', 'Produce a concise orientation brief.'),
    ],
    icon: 'document',
    id: 'github.summarizeRepo',
    popularity: 0.64,
    requiredAiTools: ['summarization', 'code-analysis'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'content.generateDocumentation', title: 'Generate Documentation' },
      { actionId: 'memory.saveContext', title: 'Save To Memory' },
    ],
    supportedContexts: [{ hostIncludes: ['github.com'] }],
    tags: ['github', 'repository', 'knowledge'],
    title: 'Summarize Repository',
  }),
  action({
    aliases: ['commit', 'commit message', 'git message'],
    artifactsProduced: [{ format: 'Markdown', title: 'Commit message' }],
    category: 'coding',
    description: 'Draft a clear commit message from visible repository changes.',
    estimatedDurationSec: 12,
    executionPlan: [
      step('read-change', 'Read change', 'Capture visible diff and discussion context.'),
      step('name-impact', 'Name impact', 'Identify user-facing and technical impact.'),
      step('draft-message', 'Draft message', 'Write a concise commit message.'),
    ],
    icon: 'git',
    id: 'github.generateCommit',
    popularity: 0.58,
    requiredAiTools: ['writing', 'code-analysis'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'github.reviewPr', title: 'Review PR' }],
    supportedContexts: [{ hostIncludes: ['github.com'] }],
    tags: ['github', 'git', 'developer'],
    title: 'Generate Commit',
  }),
  action({
    aliases: ['yt', 'youtube', 'video summary'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Video summary' },
      { format: 'Notes', title: 'Key takeaways' },
    ],
    category: 'learning',
    description: 'Summarize the current video and extract the important takeaways.',
    estimatedDurationSec: 22,
    executionPlan: [
      step('read-video', 'Read video context', 'Capture title, metadata, and available transcript context.'),
      step('extract-themes', 'Extract themes', 'Identify main ideas, examples, and claims.'),
      step('summarize-video', 'Summarize video', 'Produce a compact learning summary.'),
    ],
    icon: 'video',
    id: 'youtube.summarize',
    popularity: 0.84,
    requiredAiTools: ['video-transcript', 'summarization'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'youtube.chapters', title: 'Extract Chapters' },
      { actionId: 'youtube.notes', title: 'Generate Notes' },
    ],
    supportedContexts: [{ hostIncludes: ['youtube.com'] }, { pageKinds: ['video'] }],
    tags: ['youtube', 'video', 'summary'],
    title: 'Summarize Video',
  }),
  action({
    aliases: ['chapters', 'timestamps', 'timeline'],
    artifactsProduced: [{ format: 'Table', title: 'Video chapters' }],
    category: 'learning',
    description: 'Extract chapters and timestamps from the current video.',
    estimatedDurationSec: 24,
    executionPlan: [
      step('read-transcript', 'Read transcript', 'Use transcript and visible video metadata.'),
      step('segment-video', 'Segment video', 'Group the video into coherent chapters.'),
      step('write-timeline', 'Write timeline', 'Return chapters with timestamps and labels.'),
    ],
    icon: 'list',
    id: 'youtube.chapters',
    popularity: 0.7,
    requiredAiTools: ['video-transcript'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'youtube.notes', title: 'Generate Notes' }],
    supportedContexts: [{ hostIncludes: ['youtube.com'] }, { pageKinds: ['video'] }],
    tags: ['youtube', 'chapters', 'timeline'],
    title: 'Extract Chapters',
  }),
  action({
    aliases: ['notes', 'study notes', 'video notes'],
    artifactsProduced: [{ format: 'Notes', title: 'Study notes' }],
    category: 'learning',
    description: 'Turn the current video into structured notes.',
    estimatedDurationSec: 26,
    executionPlan: [
      step('read-source', 'Read source', 'Capture video title, transcript, and metadata.'),
      step('structure-notes', 'Structure notes', 'Group ideas into reusable notes.'),
      step('write-notes', 'Write notes', 'Produce study-ready notes.'),
    ],
    icon: 'document',
    id: 'youtube.notes',
    popularity: 0.72,
    requiredAiTools: ['video-transcript', 'note-generation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'memory.saveContext', title: 'Save To Memory' }],
    supportedContexts: [{ hostIncludes: ['youtube.com'] }, { pageKinds: ['video'] }],
    tags: ['youtube', 'notes', 'learning'],
    title: 'Generate Notes',
  }),
  action({
    aliases: ['reply', 'respond', 'email response'],
    artifactsProduced: [{ format: 'Markdown', title: 'Email reply draft' }],
    category: 'email',
    description: 'Draft a reply using the current email thread and tone.',
    estimatedDurationSec: 20,
    executionPlan: [
      step('read-thread', 'Read thread', 'Capture visible email thread and recipient context.'),
      step('infer-intent', 'Infer intent', 'Identify what needs to be answered or decided.'),
      step('draft-reply', 'Draft reply', 'Write a concise reply in the right tone.'),
    ],
    icon: 'mail',
    id: 'email.reply',
    popularity: 0.82,
    requiredAiTools: ['writing', 'email-context'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'email.improveDraft', title: 'Improve Draft' },
      { actionId: 'email.translate', title: 'Translate Email' },
    ],
    supportedContexts: [{ pageKinds: ['email'] }],
    tags: ['email', 'reply', 'draft'],
    title: 'Reply To Email',
  }),
  action({
    aliases: ['improve email', 'polish draft', 'fix grammar'],
    artifactsProduced: [{ format: 'Markdown', title: 'Improved draft' }],
    category: 'email',
    description: 'Improve the active draft for clarity, tone, and brevity.',
    estimatedDurationSec: 14,
    executionPlan: [
      step('read-draft', 'Read draft', 'Capture the active editable draft.'),
      step('improve-tone', 'Improve tone', 'Preserve intent while improving clarity.'),
      step('return-draft', 'Return draft', 'Provide an improved version ready to use.'),
    ],
    icon: 'write',
    id: 'email.improveDraft',
    popularity: 0.76,
    requiredAiTools: ['writing'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'email.reply', title: 'Reply To Email' }],
    supportedContexts: [{ pageKinds: ['email'] }, { requiresEditableTarget: true }],
    tags: ['email', 'draft', 'writing'],
    title: 'Improve Draft',
  }),
  action({
    aliases: ['translate email', 'language', 'translate'],
    artifactsProduced: [{ format: 'Markdown', title: 'Translated text' }],
    category: 'email',
    description: 'Translate selected or visible email text.',
    estimatedDurationSec: 16,
    executionPlan: [
      step('read-text', 'Read text', 'Capture selected or visible email text.'),
      step('detect-language', 'Detect language', 'Infer source language and target intent.'),
      step('translate-text', 'Translate text', 'Return a faithful translation.'),
    ],
    icon: 'translate',
    id: 'email.translate',
    popularity: 0.62,
    requiredAiTools: ['translation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'email.reply', title: 'Reply To Email' }],
    supportedContexts: [{ pageKinds: ['email'] }, { requiresSelection: true }],
    tags: ['email', 'translation', 'language'],
    title: 'Translate Email',
  }),
  action({
    aliases: ['email summary', 'summarize thread', 'thread summary'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Thread summary' },
      { format: 'Checklist', title: 'Action items' },
    ],
    category: 'email',
    description: 'Summarize the current email thread and action items.',
    estimatedDurationSec: 18,
    executionPlan: [
      step('read-thread', 'Read thread', 'Capture visible messages and participants.'),
      step('extract-actions', 'Extract actions', 'Identify decisions, asks, and deadlines.'),
      step('summarize-thread', 'Summarize thread', 'Return a compact thread brief.'),
    ],
    icon: 'mail',
    id: 'email.summarizeThread',
    popularity: 0.68,
    requiredAiTools: ['summarization', 'email-context'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'email.reply', title: 'Reply To Email' }],
    supportedContexts: [{ pageKinds: ['email'] }],
    tags: ['email', 'summary', 'thread'],
    title: 'Summarize Email Thread',
  }),
  action({
    aliases: ['research', 'find sources', 'compare sources'],
    artifactsProduced: [
      { format: 'Markdown', title: 'Research brief' },
      { format: 'Table', title: 'Source comparison' },
    ],
    category: 'research',
    description: 'Research this topic across trusted sources and return concise findings.',
    estimatedDurationSec: 38,
    executionPlan: [
      step('define-topic', 'Define topic', 'Use page context and selection to scope the research.'),
      step('compare-sources', 'Compare sources', 'Gather and compare trustworthy sources.'),
      step('write-brief', 'Write brief', 'Return findings with caveats and next steps.'),
    ],
    icon: 'search',
    id: 'research.topic',
    popularity: 0.78,
    requiredAiTools: ['web-research', 'summarization'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [
      { actionId: 'memory.saveContext', title: 'Save To Memory' },
      { actionId: 'content.generateDocumentation', title: 'Generate Documentation' },
    ],
    supportedContexts: [],
    tags: ['research', 'sources', 'topic'],
    title: 'Research Topic',
  }),
  action({
    aliases: ['translate article', 'translate page', 'language'],
    artifactsProduced: [{ format: 'Markdown', title: 'Translated article' }],
    category: 'writing',
    description: 'Translate the current article or selected passage.',
    estimatedDurationSec: 24,
    executionPlan: [
      step('read-article', 'Read article', 'Capture article or selected text.'),
      step('detect-language', 'Detect language', 'Infer source language and target tone.'),
      step('translate-article', 'Translate article', 'Return a readable translation.'),
    ],
    icon: 'translate',
    id: 'article.translate',
    popularity: 0.6,
    requiredAiTools: ['translation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'page.summarize', title: 'Summarize Page' }],
    supportedContexts: [{ pageKinds: ['article', 'document'] }, { requiresSelection: true }],
    tags: ['article', 'translation', 'writing'],
    title: 'Translate Article',
  }),
  action({
    aliases: ['tables', 'facts', 'entities', 'structured data'],
    artifactsProduced: [{ format: 'Table', title: 'Extracted data' }],
    category: 'research',
    description: 'Extract facts, entities, or tables into structured data.',
    estimatedDurationSec: 24,
    executionPlan: [
      step('scan-content', 'Scan content', 'Find repeated fields, tables, and entities.'),
      step('normalize-data', 'Normalize data', 'Structure values into consistent columns.'),
      step('return-table', 'Return table', 'Attach an exportable table artifact.'),
    ],
    icon: 'table',
    id: 'data.extractStructured',
    popularity: 0.7,
    requiredAiTools: ['extraction'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'memory.saveContext', title: 'Save To Memory' }],
    supportedContexts: [{ pageKinds: ['article', 'document', 'generic', 'pdf'] }],
    tags: ['data', 'table', 'extract'],
    title: 'Extract Structured Data',
  }),
  action({
    aliases: ['meeting notes', 'notes', 'summary notes'],
    artifactsProduced: [
      { format: 'Notes', title: 'Meeting notes' },
      { format: 'Checklist', title: 'Action items' },
    ],
    category: 'meetings',
    description: 'Create meeting notes from a transcript, document, or selected text.',
    estimatedDurationSec: 28,
    executionPlan: [
      step('read-transcript', 'Read transcript', 'Capture meeting-like text or document context.'),
      step('extract-decisions', 'Extract decisions', 'Find decisions, owners, and dates.'),
      step('write-notes', 'Write notes', 'Produce clear notes and action items.'),
    ],
    icon: 'notes',
    id: 'meeting.createNotes',
    popularity: 0.66,
    requiredAiTools: ['summarization', 'note-generation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'memory.saveContext', title: 'Save To Memory' }],
    supportedContexts: [{ pageKinds: ['document'] }, { requiresSelection: true }],
    tags: ['meeting', 'notes', 'actions'],
    title: 'Create Meeting Notes',
  }),
  action({
    aliases: ['regex', 'regular expression', 'pattern'],
    artifactsProduced: [{ format: 'Markdown', title: 'Regex explanation' }],
    category: 'coding',
    description: 'Build a regex from a plain-language goal or selected examples.',
    estimatedDurationSec: 18,
    executionPlan: [
      step('read-examples', 'Read examples', 'Use selected examples or page context.'),
      step('design-pattern', 'Design pattern', 'Create a regex and explain tradeoffs.'),
      step('provide-tests', 'Provide tests', 'Return sample matches and misses.'),
    ],
    icon: 'code',
    id: 'code.buildRegex',
    popularity: 0.56,
    requiredAiTools: ['code-generation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'code.generateTests', title: 'Generate Tests' }],
    supportedContexts: [{ requiresSelection: true }, { pageKinds: ['code', 'document', 'generic'] }],
    tags: ['regex', 'code', 'developer'],
    title: 'Build A Regex',
  }),
  action({
    aliases: ['sql', 'query', 'database query'],
    artifactsProduced: [{ format: 'Markdown', title: 'SQL query' }],
    category: 'coding',
    description: 'Write SQL from a plain-language question or selected schema.',
    estimatedDurationSec: 24,
    executionPlan: [
      step('read-question', 'Read question', 'Capture the data question and available schema.'),
      step('design-query', 'Design query', 'Choose joins, filters, grouping, and measures.'),
      step('write-sql', 'Write SQL', 'Return runnable SQL with assumptions.'),
    ],
    icon: 'database',
    id: 'code.writeSql',
    popularity: 0.58,
    requiredAiTools: ['code-generation'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'selection.explain', title: 'Explain Code' }],
    supportedContexts: [{ requiresSelection: true }, { pageKinds: ['code', 'document'] }],
    tags: ['sql', 'database', 'developer'],
    title: 'Write SQL',
  }),
  action({
    aliases: ['remember', 'save context', 'pin context'],
    artifactsProduced: [{ format: 'Notes', title: 'Saved context' }],
    category: 'productivity',
    description: 'Save useful context for later workflows.',
    estimatedDurationSec: 10,
    executionPlan: [
      step('capture-context', 'Capture context', 'Collect title, URL, selected text, and summary.'),
      step('label-memory', 'Label memory', 'Create a reusable memory label.'),
      step('save-memory', 'Save memory', 'Attach context for future actions.'),
    ],
    icon: 'memory',
    id: 'memory.saveContext',
    popularity: 0.64,
    requiredAiTools: ['memory'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'research.topic', title: 'Research Topic' }],
    supportedContexts: [],
    tags: ['memory', 'context', 'save'],
    title: 'Save To Memory',
  }),
  action({
    aliases: ['workflow', 'automation', 'multi step', 'run task'],
    artifactsProduced: [{ format: 'Checklist', title: 'Workflow plan' }],
    category: 'productivity',
    description: 'Start a reusable multi-step workflow from this context.',
    estimatedDurationSec: 42,
    executionPlan: [
      step('understand-goal', 'Understand goal', 'Use context to infer the outcome and constraints.'),
      step('plan-workflow', 'Plan workflow', 'Break the work into ordered steps.'),
      step('start-workflow', 'Start workflow', 'Run or stage the workflow in the task workspace.'),
    ],
    icon: 'workflow',
    id: 'workflow.start',
    popularity: 0.6,
    requiredAiTools: ['workflow-planning'],
    requiredPermissions: SIDEBAR_PERMISSIONS,
    suggestedFollowUps: [{ actionId: 'memory.saveContext', title: 'Save To Memory' }],
    supportedContexts: [],
    tags: ['workflow', 'automation', 'productivity'],
    title: 'Run Workflow',
  }),
];

export const FIRST_PARTY_ACTION_REGISTRY = new ActionRegistry(FIRST_PARTY_ACTIONS);

function action(input: ProductAction): ProductAction {
  return input;
}

function step(id: string, label: string, description: string) {
  return {
    description,
    id,
    label,
  };
}
